Create LICENSE
EficodeEntDemo/pluto-workflow-templates pull request #10
Opened 2021-09-21 05:36 UTC by evolaine

Adding an Apache 2.0 license.

2021-09-21 06:32 UTC, romuaa requested changes

2021-09-21 06:32 UTC, romuaa commented on LICENSE
> +       http://www.apache.org/licenses/LICENSE-2.0
Needs year and Eficode filled in.

2021-09-21 11:33 UTC, evolaine commented on LICENSE
> +       http://www.apache.org/licenses/LICENSE-2.0
Done, good catch.

2021-09-21 11:41 UTC, romuaa approved these changes

2021-09-22 05:53 UTC, mikkilevon approved these changes

2021-09-22 07:14 UTC, merged